---
id: Constraint
name: Constraint
full: Constraint library
description: A library for building constraints that evaluate to true or false.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Constraint
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.0.4
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
