---
id: Constraint
name: Constraint
full: Constraint library
description: A library for building constraints that evaluate to true or false.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Constraint
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
  optional:
    composer:
      horde/test: ^3
